version: '3.8'

services:
  db:
    image: postgres:13
    environment: 
      POSTGRES_USER: sawm
      POSTGRES_PASSWORD: hieuhc35
      POSTGRES_DB: weather_data
    volumes: 
      - weather_db:/var/lib/postgresql/data  
      - ./database:/docker-entrypoint-initdb.d
  volumes:
    weather_db:  
  backend:
    build 
