services:
  backend:
    image: ${DOCKERHUB_USERNAME}/weather-backend:latest
    ports:
      - "80:80"
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSW}@${DB_HOST}:5432/${DB_NAME}
      - API_KEY=${API_KEY}
