name: Weather App CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install python (for testing env)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: |
          pip install --no-cache-dir -r backend/requirements.txt
          pip install flake8

      - name: check syntax by flake8
        run: flake8 backend/app.py
  
  build-and-push-be:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/weather-backend:latest
            ${{secrets.DOCKERHUB_USERNAME}}/weather-backend:${{github.ref_name}}

  deploy-be:
    needs: build-and-push-be
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Backend EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SV_IP }}
          username: ${{ secrets.SV_USER }}
          key: ${{ secrets.WF_PRV_KEY }}
          script: |
            if [ ! -d "WeatherForecast-devops-project" ]; then
              git clone https://github.com/Sawm-c/WeatherForecast-devops-project.git
            fi
            
            cd WeatherForecast-devops-project
            git pull origin main
            
            echo "DB_USER=${{ secrets.DB_USER }}" > .env
            echo "DB_PASSW=${{ secrets.DB_PASSW }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "API_KEY=${{ secrets.API_KEY }}" >> .env
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
            
            docker compose pull
            docker compose up -d


  deploy-fe:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Sync fe to s3
        run: |
          aws s3 sync ./frontend/ s3://${{ secrets.FE_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/*"
